version: "3"
services:
  instamate:
    image: pihomeserver/instamate:latest
    restart: always
    environment:
      - HOST=${INSTAMATE_HOST:-"0.0.0.0"}
      - PORT=${INSTAMATE_PORT:-"8080"}
      - SESSION_SECRET=${SESSION_SECRET:-"Your Session Secret goes here"}
      - POSTGRES_URI=${POSTGRES_URI:-"database"}
      - FACEBOOK_APPLICATIONID=${FACEBOOK_APPLICATIONID}
      - FACEBOOK_APPLICATIONSECRET=${FACEBOOK_APPLICATIONSECRET}
      - FACEBOOK_API_URL=${FACEBOOK_API_URL:-"https://graph.facebook.com/v9.0"}
      - FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL:-"https://your_reference.ngrok.io/auth/facebook/callback"}
      - POSTGRES_USER=${POSTGRES_USER:-instamate}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=instamate
      - POSTGRES_PORT=${POSTGRES_PORT:-"5432"}
    ports:
      - "${INSTAMATE_PORT}:${INSTAMATE_PORT}"
    networks:
      - instamate

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-instamate}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - POSTGRES_DB=${POSTGRES_DB:-instamate}
    volumes:
      - ./instamate-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - instamate
    restart: unless-stopped

  grafana:
    image: pihomeserver/pihomeserver-instamate:latest
    environment:
      - DATABASE_USER=${POSTGRES_USER:-instamate}
      - DATABASE_PASS=${POSTGRES_PASSWORD:-secret}
      - DATABASE_NAME=${POSTGRES_DB:-instamate}
      - DATABASE_HOST=${POSTGRES_URI:-database}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - instamate-grafana-data:/var/lib/grafana
    networks:
      - instamate
    restart: unless-stopped

networks:
  instamate:
    driver: bridge

volumes:
    postgres:
    instamate-grafana-data: