{
 "title": "Audience evolution",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "title": "Top 10 countries evolution",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date as time,\n  key,\n  value\nFROM\n  \"UserLifetimeInsights\"\nWHERE\n  insight_type = 'audience_country'\n  and instagram_business_account = $user_id\n  and key in (\n    SELECT\n      key\n    FROM\n      \"UserLifetimeInsights\"\n    WHERE\n      insight_type = 'audience_country'\n      and instagram_business_account = $user_id\n      and insight_date = (\n        select max(insight_date)\n        from \"UserLifetimeInsights\" \n        where insight_type = 'audience_country' \n          and instagram_business_account = $user_id)\n      order by value desc\n      limit 10)\norder by insight_date asc, value desc\n"
    }
   ]
  },
  {
   "title": "Top 10 locale evolution",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date as time,\n  substring(key, 1, 2) as locale, \n  sum(value) as sumLocale\nFROM\n  \"UserLifetimeInsights\"\nWHERE\n  insight_type = 'audience_locale'\n  and instagram_business_account = $user_id\n  and substring(key, 1, 2) in (\n    SELECT\n      substring(key, 1, 2)\n    FROM\n      \"UserLifetimeInsights\"\n    WHERE\n      insight_type = 'audience_locale'\n      and instagram_business_account = $user_id\n      and insight_date = (\n        select max(insight_date)\n        from \"UserLifetimeInsights\" \n        where insight_type = 'audience_country' \n          and instagram_business_account = $user_id)\n      order by value desc\n      limit 10)\ngroup by insight_date, locale\norder by insight_date asc, sumLocale desc\n"
    }
   ]
  },
  {
   "title": "Audience gender",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date as time,\n  substring(key, 1, 1) as metric,\n  sum(value) as sumLocale\nFROM\n  \"UserLifetimeInsights\"\nWHERE\n  insight_type = 'audience_gender_age'\n  and instagram_business_account = $user_id\ngroup by insight_date, metric\norder by insight_date asc, sumLocale desc"
    }
   ]
  }
 ]
}