{
 "title": "Detailed profile",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  profile_picture_url\nFROM \"UserProfiles\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Media",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  media_count\nFROM \"UserInsights\"\nWHERE\n  instagram_business_account = $user_id\nORDER BY insight_date desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  followers_count\nFROM \"UserInsights\"\nWHERE\n  instagram_business_account = $user_id\nORDER BY insight_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Follows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  follows_count\nFROM \"UserInsights\"\nWHERE\n  instagram_business_account = $user_id\nORDER BY insight_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Likes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(like_count)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(comments_count)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Saved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select sum(reqSaved.totalSaved) \nfrom (select distinct(mi.media_id), max(mi.saved) as totalSaved\nfrom \"MediaInsights\" mi, \"Media\" m\nwhere saved is not null and mi.media_id = m.media_id and m.instagram_business_account = $user_id\ngroup by mi.media_id) as reqSaved"
    }
   ]
  },
  {
   "title": "ER Lifetime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH mediaCounts as (\nSELECT\n  sum(like_count) as likeCount,\n  sum(comments_count) as commentsCount\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id\n), savedCount as (\nselect sum(reqSaved.totalSaved) as totSaved\nfrom (select distinct(media_id), max(saved) as totalSaved\nfrom \"MediaInsights\" mi\nwhere saved is not null\ngroup by media_id) as reqSaved)\n\nSELECT\n  cast ((mediaCounts.likeCount + mediaCounts.commentsCount + savedCount.totSaved) as float) / followers_count as engRate\nFROM \"UserInsights\", mediaCounts, savedCount\nWHERE\n  instagram_business_account = $user_id\nORDER by insight_date desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Published media per type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  media_type,\n  count(media_id) as total\nFROM\n  \"Media\"\ngroup by media_type\norder by total desc"
    }
   ]
  },
  {
   "title": "Avg Likes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast (sum(like_count) as float) / count(media_id)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Avg Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  cast (sum(comments_count) as float) / count(media_id)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Avg Saved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select cast (sum(reqSaved.totalSaved) as float) / count(reqSaved.totalMedia)\nfrom (select distinct(mi.media_id), max(mi.saved) as totalSaved, count(m.media_id) as totalMedia\nfrom \"MediaInsights\" mi, \"Media\" m\nwhere saved is not null and mi.media_id = m.media_id and m.instagram_business_account = $user_id\ngroup by mi.media_id) as reqSaved"
    }
   ]
  },
  {
   "title": "ER Last 20 posts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "WITH engTotal as (\nselect sum(engAll) as eng\nfrom (\n\tselect max(engagement) as engAll\n\tfrom \"MediaInsights\" mi\n\twhere mi.media_id in (select media_id from \"Media\" order by \"timestamp\" desc limit 20)\n\tgroup by mi.media_id \n\t) as engList\n)\n\nSELECT\n  cast (engTotal.eng as float)*100/20 / followers_count as engRate\nFROM \"UserInsights\", engTotal\nWHERE\n  instagram_business_account = $user_id\nORDER by insight_date desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Detailed audience split",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "with gainsData as (select\n\tui.insight_date::date,\n\tui.followers_count, ui.followers_count - lag(ui.followers_count, 1) over() as followerGain,\n\tui.follows_count, ui.follows_count - lag(ui.follows_count, 1) over() as followsGain,\n\tui.media_count, ui.media_count - lag(ui.media_count, 1) over() as mediaGain\nfrom \"UserInsights\" ui \nwhere ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  followers_count, followerGain,\n  follows_count, followsGain,\n  media_count, mediaGain\nfrom\n  gainsData\nwhere $__timeFilter(insight_date)\norder by insight_date desc"
    }
   ]
  },
  {
   "title": "Instagram growth",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with gainsData as (select\n\tui.insight_date::date,\n\tui.followers_count, ui.followers_count - lag(ui.followers_count, 1) over() as followerGain,\n\tui.follows_count, ui.follows_count - lag(ui.follows_count, 1) over() as followsGain,\n\tui.media_count, ui.media_count - lag(ui.media_count, 1) over() as mediaGain\nfrom \"UserInsights\" ui \nwhere ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  followerGain,\n  followsGain,\n  mediaGain\nfrom\n  gainsData\nwhere $__timeFilter(insight_date)"
    }
   ]
  },
  {
   "title": "Followers split",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with gainsData as (select\n  ui.insight_date::date,\n\tudi.follower_count as newFollowers,\n\t@(ui.followers_count - lag(ui.followers_count, 1) over ()) as gainFollowers,\n\t@(udi.follower_count - (ui.followers_count - lag(ui.followers_count, 1) over ())) as lostFollowers\nfrom \"UserInsights\" ui \nleft join \"UserDetailedInsights\" udi on \n  ui.insight_date::date = udi.insight_date::date and \n  ui.instagram_business_account=udi.instagram_business_account\nwhere \n  ui.instagram_business_account = $user_id and\n  udi.follower_count is not null and\n  ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere ui.instagram_business_account = $user_id\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  newFollowers,\n  gainFollowers,\n  lostFollowers\nfrom gainsData\nwhere $__timeFilter(insight_date)\norder by insight_date asc"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  followers_count\nFROM \"UserInsights\"\nWHERE\n  $__timeFilter(insight_date)\n  and instagram_business_account = $user_id\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total likes growth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Likes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  likes_count\nFROM \"UserInsights\"\nWHERE\n  $__timeFilter(insight_date)\n  and instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Follows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  follows_count\nFROM \"UserInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Media",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  media_count\nFROM \"UserInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Email contacts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  email_contacts \nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Impressions & Reach",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  impressions,\n  reach\nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Profile views",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  profile_views \nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reach",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  reach \nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Click in biography",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  text_message_clicks \nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Website clicks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  insight_date AS \"time\",\n  website_clicks \nFROM \"UserDetailedInsights\"\nWHERE\n  $__timeFilter(insight_date)\nORDER BY 1"
    }
   ]
  }
 ]
}