{
 "title": "Detailed audience",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "title": "Detailed audience split",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "with gainsData as (select\n\tui.insight_date::date,\n\tui.followers_count, ui.followers_count - lag(ui.followers_count, 1) over() as followerGain,\n\tui.follows_count, ui.follows_count - lag(ui.follows_count, 1) over() as followsGain,\n\tui.media_count, ui.media_count - lag(ui.media_count, 1) over() as mediaGain\nfrom \"UserInsights\" ui \nwhere ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  followers_count, followerGain,\n  follows_count, followsGain,\n  media_count, mediaGain\nfrom\n  gainsData\nwhere $__timeFilter(insight_date)\norder by insight_date desc"
    }
   ]
  },
  {
   "title": "Audience location",
   "type": "grafana-map-panel",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(insight_date), key, value\nFROM \"UserLifetimeInsights\"\nWHERE\n  instagram_business_account = $user_id\n  and insight_type = 'country'\n  and insight_date in (\n    select max(insight_date)\n    from \"UserLifetimeInsights\" uli\n    where instagram_business_account = $user_id \n      and insight_type = 'country')\n"
    }
   ]
  },
  {
   "title": "Instagram growth on time range",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with gainsData as (select\n\tui.insight_date::date,\n\tui.followers_count, ui.followers_count - lag(ui.followers_count, 1) over() as followerGain,\n\tui.follows_count, ui.follows_count - lag(ui.follows_count, 1) over() as followsGain,\n\tui.media_count, ui.media_count - lag(ui.media_count, 1) over() as mediaGain\nfrom \"UserInsights\" ui \nwhere ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  followerGain,\n  followsGain,\n  mediaGain\nfrom\n  gainsData\nwhere $__timeFilter(insight_date)"
    }
   ]
  },
  {
   "title": "Followers split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with gainsData as (select\n  ui.insight_date::date,\n\tudi.follower_count as newFollowers,\n\t@(ui.followers_count - lag(ui.followers_count, 1) over ()) as gainFollowers,\n\t@(udi.follower_count - (ui.followers_count - lag(ui.followers_count, 1) over ())) as lostFollowers\nfrom \"UserInsights\" ui \nleft join \"UserDetailedInsights\" udi on \n  ui.insight_date::date = udi.insight_date::date and \n  ui.instagram_business_account=udi.instagram_business_account\nwhere \n  ui.instagram_business_account = $user_id and\n  udi.follower_count is not null and\n  ui.insight_date in (\n  \tselect max(ui.insight_date) as lastInsight\n  \tfrom \"UserInsights\" ui\n  \twhere ui.instagram_business_account = $user_id\n  \tgroup by ui.insight_date::date\n  )\n  and extract(epoch from ui.insight_date)*1000 > $__from - 86400000\n)\n\nselect \n  $__time(insight_date),\n  newFollowers,\n  gainFollowers,\n  lostFollowers\nfrom gainsData\nwhere $__timeFilter(insight_date)\norder by insight_date asc"
    }
   ]
  }
 ]
}