{
 "title": "Feed",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "title": "Feed",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "with currentFollowers as (\n  SELECT followers_count\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n), maxMediaInsight as (select\n\tmedia_id, max(\"createdAt\") as last_insight\nfrom \"MediaInsights\" mi\ngroup by mi.media_id)\n\nselect\n\tm.media_id,\n\t1000 * extract(epoch from timestamp::timestamp) as tsp,\n  $__time(timestamp),\n  concat('<img width=\"70px\" height\"70px\" src=\"',case when media_type = 'VIDEO' then thumbnail_url\n    else media_url\n  end, '\"/>') as media_image,\n  mi.like_count,\n  mi.comments_count, \n  mi.saved,\n\t(cast (mi.engagement as float) / currentFollowers.followers_count)*100 as er_post,\n\t((cast (mi.comments_count as float) + mi.comments_count + mi.like_count + mi.saved)/ currentFollowers.followers_count)*100 as er_factored,\n\t(cast (mi.reach as float) / currentFollowers.followers_count)*100 as er_reach,\n\t(cast (mi.impressions as float) / currentFollowers.followers_count)*100 as er_impressions\nfrom\n\t\"Media\" m, \n\t\"MediaInsights\" mi,\n\tmaxMediaInsight, \n\tcurrentFollowers\nwhere\n\tm.media_id = maxMediaInsight.media_id\n\tand m.instagram_business_account = $user_id\n\tand m.media_id = mi.media_id \n\tand mi.\"createdAt\" = maxMediaInsight.last_insight\n\tand extract(epoch from m.\"timestamp\"::date)*1000 >= $__from\norder by m.\"timestamp\" desc \n--limit 20"
    }
   ]
  },
  {
   "title": "Avg Likes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(like_count)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id\n  and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Engagements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "with currentFollowers as (\n  SELECT followers_count\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n), maxMediaInsight as (select\n\tmedia_id, max(\"createdAt\") as last_insight\nfrom \"MediaInsights\" mi\ngroup by mi.media_id)\n\nselect\n  $__time(timestamp::date),\n\t(cast (mi.engagement as float) / currentFollowers.followers_count)*100 as er_post,\n\t((cast (mi.comments_count as float) + mi.comments_count + mi.like_count + mi.saved)/ currentFollowers.followers_count)*100 as er_factored,\n\t(cast (mi.reach as float) / currentFollowers.followers_count)*100 as er_reach,\n\t(cast (mi.impressions as float) / currentFollowers.followers_count)*100 as er_impressions\nfrom\n\t\"Media\" m, \n\t\"MediaInsights\" mi,\n\tmaxMediaInsight, \n\tcurrentFollowers\nwhere\n\tm.media_id = maxMediaInsight.media_id\n\tand m.instagram_business_account = $user_id\n\tand m.media_id = mi.media_id \n\tand mi.\"createdAt\" = maxMediaInsight.last_insight\n\tand $__timeFilter(m.timestamp)\n--\tand extract(epoch from m.\"timestamp\"::date)*1000 >= $__from\norder by m.\"timestamp\" asc "
    }
   ]
  },
  {
   "title": "Published media per type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(media_id) as value,\n  media_type as metric\nFROM\n  \"Media\"\nwhere instagram_business_account = $user_id\nGROUP BY 3\nORDER BY metric DESC;\n"
    }
   ]
  },
  {
   "title": "Avg Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(comments_count)\nFROM \"Media\"\nWHERE\n  instagram_business_account = $user_id\n  and $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Avg Saved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select avg(reqSaved.totalSaved)\nfrom (\n  select distinct(mi.media_id), max(mi.saved) as totalSaved\n  from \"MediaInsights\" mi, \"Media\" m\n  where saved is not null\n    and mi.media_id = m.media_id\n    and m.instagram_business_account = $user_id\n    and $__timeFilter(m.timestamp)\n  group by mi.media_id) as reqSaved"
    }
   ]
  }
 ]
}