{
 "title": "Media comparison",
 "tags": [ "instamate" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:15:58.800Z" },
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   },
   {
    "name": "media_1",
    "label": "First media",
    "query": "SELECT media_id AS __value, timestamp AS __text FROM public.\"Media\" order by timestamp desc;"
   },
   {
    "name": "media_2",
    "label": "Second media",
    "query": "SELECT media_id AS __value, timestamp AS __text FROM public.\"Media\" order by timestamp desc;"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "title": "Media likes comparison",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  extract(epoch from \"createdAt\"::timestamp) - (select min(extract(epoch from \"createdAt\"::timestamp)) from \"MediaInsights\" WHERE media_id = '$media_1') as time,\n  like_count as likesMedia1\nfrom \"MediaInsights\"\nWHERE media_id = '$media_1'\norder by time asc"
    },
    {
     "rawSql": "SELECT\n  extract(epoch from \"createdAt\"::timestamp) - (select min(extract(epoch from \"createdAt\"::timestamp)) from \"MediaInsights\" WHERE media_id = '$media_2') as time,\n  like_count as likesMedia2\nfrom \"MediaInsights\"\nWHERE media_id = '$media_2'\norder by time asc"
    }
   ]
  },
  {
   "title": "First media",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  case when media_type = 'VIDEO' then thumbnail_url\n       when media_type = 'REELS' then thumbnail_url\n       else media_url\n  end\nFROM\n  \"Media\"\nWHERE \n  media_id = '$media_1'"
    }
   ]
  },
  {
   "title": "Second media",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  case when media_type = 'VIDEO' then thumbnail_url\n       when media_type = 'REELS' then thumbnail_url\n       else media_url\n  end\nFROM\n  \"Media\"\nWHERE \n  media_id = '$media_2'"
    }
   ]
  }
 ]
}