{
 "title": "Media",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "media_id", "query": "17888266264925052" },
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  case when media_type = 'VIDEO' then thumbnail_url\n       when media_type = 'REELS' then thumbnail_url\n       else media_url\n  end\nFROM \"Media\"\nWHERE\n  media_id = '$media_id'"
    }
   ]
  },
  {
   "title": "Published on",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp\nFROM \"Media\"\nWHERE \n  media_id = '$media_id'"
    }
   ]
  },
  {
   "title": "Likes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  like_count\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id'\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  comments_count\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id'\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Saved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Saved\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id' and\n  Saved is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  impressions\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id' and\n  impressions is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Reach",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reach\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id' and\n  reach is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Views (videos)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  mi.video_views\nFROM \"MediaInsights\" as mi, \"Media\" as m\nWHERE \n  mi.media_id = '$media_id' and\n  m.media_id = '$media_id' and\n  m.media_type = 'VIDEO' and\n  mi.video_views is not null\nORDER by mi.\"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Published for",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "time: YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  justify_interval(now()::timestamp(0) - timestamp::timestamp(0)) as duration\nFROM \"Media\"\nWHERE \n  media_id = '$media_id'"
    }
   ]
  },
  {
   "title": "Engagement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  engagement\nFROM \"MediaInsights\"\nWHERE \n  media_id = '$media_id'\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "ER Post",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH uData as (\n  SELECT followers_count\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n)\n\nSELECT\n  (cast (m.engagement as float) / uData.followers_count)*100\nFROM \"MediaInsights\" as m, uData\nWHERE \n  m.media_id = '$media_id' and\n  m.reach is not null\nORDER by m.\"createdAt\" desc \nlimit 1"
    }
   ]
  },
  {
   "title": "ER Factored",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH uData as (\n  SELECT followers_count, instagram_business_account\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n)\n\nSELECT\n  ((cast (m.comments_count as float) + m.comments_count + m.like_count + m.saved)/ uData.followers_count)*100\nFROM \"MediaInsights\" as m, uData\nWHERE \n  m.media_id = '$media_id' and\n  m.reach is not null\nORDER by m.\"createdAt\" desc \nlimit 1"
    }
   ]
  },
  {
   "title": "ER Impressions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH uData as (\n  SELECT followers_count, instagram_business_account\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n)\n\nSELECT\n  (cast (m.impressions as float) / uData.followers_count)*100\nFROM \"MediaInsights\" as m, uData\nWHERE \n  m.media_id = '$media_id' and\n  m.reach is not null\nORDER by m.\"createdAt\" desc \nlimit 1"
    }
   ]
  },
  {
   "title": "ER Reach",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH uData as (\n  SELECT followers_count, instagram_business_account\n  FROM \"UserInsights\"\n  WHERE instagram_business_account = $user_id\n  ORDER BY insight_date desc\n  LIMIT 1\n)\n\nSELECT\n  (cast (m.reach as float) / uData.followers_count)*100\nFROM \"MediaInsights\" as m, uData\nWHERE \n  m.media_id = '$media_id' and\n  m.reach is not null\nORDER by m.\"createdAt\" desc \nlimit 1"
    }
   ]
  },
  {
   "title": "Likes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  like_count\nFROM\n  \"MediaInsights\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  media_id = '$media_id'\norder by \"createdAt\" asc\n"
    }
   ]
  },
  {
   "title": "Comments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  comments_count\nFROM\n  \"MediaInsights\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  media_id = '$media_id'\norder by \"createdAt\" ASC\n"
    }
   ]
  }
 ]
}