{
 "title": "Overview",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-1M", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  profile_picture_url\nFROM \"UserProfiles\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Biography",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  biography\nFROM \"UserProfiles\"\nWHERE\n  instagram_business_account = $user_id"
    }
   ]
  },
  {
   "title": "Media",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  media_count\nFROM \"UserInsights\"\nWHERE\n  instagram_business_account = $user_id\nORDER BY insight_date desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Followers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  followers_count\nFROM \"UserInsights\"\nWHERE\n  instagram_business_account = $user_id\nORDER BY insight_date DESC\nLIMIT 1"
    }
   ]
  }
 ]
}