{
 "title": "Story",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "media_id", "query": "17850562037450031" },
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  case when s.media_type = 'VIDEO' then s.thumbnail_url\n      else s.media_url\n  end\nFROM \"Story\" s\nWHERE\n  media_id = '$media_id'"
    }
   ]
  },
  {
   "title": "Exits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  exits\nFROM \"StoryInsights\"\nWHERE \n  media_id = '$media_id' and\n  exits is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  impressions\nFROM \"StoryInsights\"\nWHERE \n  media_id = '$media_id' and\n  impressions is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Reach",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  reach\nFROM \"StoryInsights\"\nWHERE \n  media_id = '$media_id' and\n  reach is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Taps fwd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  taps_forward\nFROM \"StoryInsights\"\nWHERE \n  media_id = '$media_id' and\n  taps_forward is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Taps back",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  taps_back\nFROM \"StoryInsights\"\nWHERE \n  media_id = '$media_id' and\n  taps_back is not null\nORDER by \"createdAt\" desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Impressions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  impressions\nFROM \"StoryInsights\"\nWHERE\n  media_id = '$media_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reach",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  reach\nFROM\n  \"StoryInsights\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  media_id = '$media_id'\norder by \"createdAt\" asc\n"
    }
   ]
  }
 ]
}