{
 "title": "Stories",
 "tags": [ "InstaMate" ],
 "time": { "from": "now-1M", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "user_id",
    "label": "user_id",
    "query": "SELECT instagram_business_account AS __value, name AS __text FROM public.\"Pages\";"
   }
  ]
 },
 "panels": [
  { "title": "$user_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "user_id" },
  {
   "title": "Stories",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH topInsights as (\n  select \n    media_id,\n    max(exits) as exits, \n    max(impressions) as impressions, \n    max(reach) as reach, \n    max(taps_forward) as taps_forward, \n    max(taps_back) as taps_back,\n    max(\"createdAt\")\n  from \"StoryInsights\"\n  group by media_id\n)\n\nSELECT\n  s.media_id,\n  1000 * extract(epoch from s.timestamp::timestamp) as tspFrom,\n  ((1000 * extract(epoch from s.timestamp::timestamp)) + 86400000) as tspTo,\n  $__time(s.timestamp),\n  concat('<img width=\"70px\" height\"70px\" src=\"',case when media_type = 'VIDEO' then thumbnail_url\n    else media_url\n  end, '\"/>') as media_image,\n  topInsights.exits,\n  topInsights.impressions,\n  topInsights.reach,\n  topInsights.taps_forward,\n  topInsights.taps_back\nFROM \"Story\" s, topInsights\nwhere \n  s.media_id = topInsights.media_id\n  and $__timeFilter(s.timestamp)\nORDER BY s.timestamp desc"
    }
   ]
  },
  {
   "title": "Published stories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  count(media_id)\nfrom\n  \"Story\"\nwhere $__timeFilter(timestamp)\nand instagram_business_account = $user_id\n"
    }
   ]
  },
  {
   "title": "Impressions & reach",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH topInsights as (\n  select \n    media_id,\n    max(impressions) as impressions, \n    max(reach) as reach, \n    max(\"createdAt\") as lastInsightDate\n  from \"StoryInsights\"\n  group by media_id\n)\n\nSELECT\n  $__time(s.timestamp::timestamp),\n  topInsights.reach,\n  topInsights.impressions\nFROM \"Story\" s, topInsights\nwhere \n  s.media_id = topInsights.media_id\n  and $__timeFilter(s.timestamp::timestamp)\norder by s.timestamp asc"
    }
   ]
  },
  {
   "title": "Average reach",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select avg(max_reach)\nfrom (\n  select max(si.reach) as max_reach\n\tfrom \"StoryInsights\" si, \"Story\" s\n\twhere s.instagram_business_account = $user_id\n\tand si.media_id = s.media_id\n\tand $__timeFilter(s.timestamp)\n\tgroup by si.media_id) maxreach\n"
    }
   ]
  },
  {
   "title": "Average impressions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select avg(imp)\nfrom (select max(impressions) as imp\n\tfrom \"StoryInsights\" si, \"Story\" s\n\twhere s.instagram_business_account = $user_id\n\tand s.media_id = si.media_id\n\tand $__timeFilter(s.timestamp)\n\tgroup by si.media_id) maximp\n"
    }
   ]
  }
 ]
}